// src/app/layout.tsx
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { NextUIProvider } from "@nextui-org/react";
import { UserProvider } from "@/context/UserContext"; 
import "./globals.css";
import ProtectedRoute from "@/components/ProtectedRoute";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <NextUIProvider>
          <UserProvider>
            <ProtectedRoute>{children}</ProtectedRoute>
          </UserProvider>
        </NextUIProvider>
      </body>
    </html>
  );
}
